name: ppg_signal_collector
description: A Flutter app to collect PPG signal and user data.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  # Use only one gallery saver package - switching to gal for better compatibility
  gal: ^2.3.0
  flex_color_picker: ^3.4.1
  fl_chart: ^0.68.0
  image: ^4.1.7

flutter:
  uses-material-design: true